version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "15672:15672"  # RabbitMQ management console
      - "5672:5672"    # RabbitMQ default port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672/api/overview" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  business-service:
    build:
      context: ./Business
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8082:8082"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - app-network

  hr:
    build:
      context: ./HR
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8083:8083"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - app-network

  finance:
    build:
      context: ./Finance
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8084:8084"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - app-network

  auth:
    build:
      context: ./Auth
    depends_on:
      - eureka-server
      - config-server
    ports:
      - "8085:8085"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - app-network


  system-events:
    build:
      context: ./SystemEventsServer
    ports:
      - "6565:6565"
      - "8087:8087"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - app-network


  config-server:
    build:
      context: ./config
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
      - GIT_REPO=https://github.com/amujkic1/Config-Repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - app-network


  test_site:
    image: nginx
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
