version: '3.9'

services:
  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 5

  business-service:
    build:
      context: ./Business
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - app-network

  hr:
    build:
      context: ./HR
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - app-network

  finance:
    build:
      context: ./Finance
    depends_on:
      - eureka-server
    ports:
      - "8084:8084"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - app-network

  system-events:
    build:
      context: ./SystemEventsServer
    ports:
      - "6565:6565"
      - "8085:8085"
    networks:
      - app-network


  test_site:
    image: nginx
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
